/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "approver" | "editor" | "user";

export interface AcknowledgmentConfirmationCodes {
  code: string;
  createdAt: Generated<Timestamp>;
  email: string;
  expiresAt: Timestamp;
  id: Generated<number>;
  policyId: number;
  portalId: number;
  used: Generated<boolean>;
}

export interface EmailBasedAcknowledgments {
  acknowledgedAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  ipAddress: string | null;
  organizationId: number;
  policyId: number;
  portalId: number;
  userAgent: string | null;
}

export interface LayoutTemplates {
  createdAt: Generated<Timestamp | null>;
  footerTemplate: string | null;
  headerTemplate: string | null;
  id: Generated<number>;
  isDefault: Generated<boolean | null>;
  metadataTemplate: string | null;
  name: string;
  type: string;
  updatedAt: Generated<Timestamp | null>;
}

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  success: Generated<boolean | null>;
}

export interface Notifications {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  isRead: Generated<boolean | null>;
  message: string;
  metadata: Generated<Json | null>;
  organizationId: number;
  readAt: Timestamp | null;
  relatedPolicyId: number | null;
  relatedUserId: number | null;
  title: string;
  type: string;
  userId: number;
}

export interface OauthAccounts {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  provider: string;
  providerEmail: string;
  providerUserId: string;
  updatedAt: Generated<Timestamp | null>;
  userId: number;
}

export interface OauthStates {
  codeVerifier: string;
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: Generated<number>;
  provider: string;
  redirectUrl: string;
  state: string;
  userId: number | null;
}

export interface OrganizationDownloadSettings {
  brandingEnabled: Generated<boolean | null>;
  createdAt: Generated<Timestamp | null>;
  dateFormat: Generated<string | null>;
  enabledFormats: Generated<Json | null>;
  footerTemplate: string | null;
  headerTemplate: string | null;
  id: Generated<number>;
  includeToc: Generated<boolean | null>;
  layoutTemplateId: number | null;
  maxFileSizeMb: Generated<number | null>;
  organizationId: number | null;
  pageNumberFormat: Generated<string | null>;
  rateLimitPerMinute: Generated<number | null>;
  showMetadata: Generated<boolean | null>;
  updatedAt: Generated<Timestamp | null>;
}

export interface Organizations {
  createdAt: Generated<Timestamp | null>;
  domain: string | null;
  id: Generated<number>;
  isActive: Generated<boolean | null>;
  name: string;
  slug: string;
  updatedAt: Generated<Timestamp | null>;
}

export interface OrganizationVariables {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  isSystemVariable: Generated<boolean | null>;
  organizationId: number | null;
  updatedAt: Generated<Timestamp | null>;
  variableName: string;
  variableValue: string | null;
}

export interface Policies {
  approvedAt: Timestamp | null;
  approvedBy: number | null;
  authorId: number;
  category: string | null;
  content: string;
  createdAt: Generated<Timestamp | null>;
  currentVersion: Generated<number | null>;
  department: string | null;
  effectiveDate: Timestamp | null;
  expirationDate: Timestamp | null;
  id: Generated<number>;
  organizationId: number;
  publishedAt: Timestamp | null;
  reviewDate: Timestamp | null;
  reviewedAt: Timestamp | null;
  reviewedBy: number | null;
  status: Generated<string>;
  tags: string[] | null;
  title: string;
  updatedAt: Generated<Timestamp | null>;
}

export interface PolicyAcknowledgments {
  acknowledgedAt: Generated<Timestamp | null>;
  id: Generated<number>;
  ipAddress: string | null;
  keyPointsConfirmedAt: Timestamp | null;
  organizationId: number;
  policyId: number;
  quizAttemptId: number | null;
  reminderCount: Generated<number | null>;
  reminderSentAt: Timestamp | null;
  understandingCompletedAt: Timestamp | null;
  userId: number;
}

export interface PolicyAssignments {
  assignedAt: Generated<Timestamp | null>;
  assignedBy: number;
  dueDate: Timestamp | null;
  id: Generated<number>;
  isMandatory: Generated<boolean | null>;
  lastReminderSentAt: Timestamp | null;
  notificationSentAt: Timestamp | null;
  organizationId: number;
  policyId: number;
  reminderCount: Generated<number | null>;
  userId: number;
}

export interface PolicyAuditLog {
  action: string;
  actionBy: number;
  actionTimestamp: Generated<Timestamp>;
  details: Json | null;
  id: Generated<number>;
  ipAddress: string | null;
  organizationId: number;
  policyId: number;
  policyName: string;
  userAgent: string | null;
}

export interface PolicyDownloads {
  downloadedAt: Generated<Timestamp | null>;
  fileSize: number | null;
  format: string;
  generationTimeMs: number | null;
  id: Generated<number>;
  ipAddress: string | null;
  policyId: number | null;
  userAgent: string | null;
  userId: number | null;
}

export interface PolicyPortalAssignments {
  assignedAt: Generated<Timestamp>;
  id: Generated<number>;
  policyId: number;
  portalId: number;
}

export interface PolicyReadingSessions {
  completionPercentage: Generated<number | null>;
  id: Generated<number>;
  organizationId: number;
  pagesVisited: Generated<number | null>;
  policyId: number;
  sessionEndedAt: Timestamp | null;
  sessionStartedAt: Generated<Timestamp | null>;
  timeSpentSeconds: Generated<number | null>;
  userId: number;
}

export interface PolicyVersions {
  category: string | null;
  changeSummary: string | null;
  content: string;
  createdAt: Generated<Timestamp | null>;
  createdBy: number;
  department: string | null;
  effectiveDate: Timestamp | null;
  expirationDate: Timestamp | null;
  id: Generated<number>;
  isPublic: Generated<boolean | null>;
  organizationId: number;
  policyId: number;
  requiresAcknowledgment: Generated<boolean | null>;
  reviewDate: Timestamp | null;
  status: string;
  tags: string[] | null;
  title: string;
  versionNumber: number;
}

export interface PortalEmailRecipients {
  addedAt: Generated<Timestamp | null>;
  createdBy: number | null;
  email: string;
  id: Generated<number>;
  organizationId: number;
  portalId: number;
}

export interface PortalLayoutOverrides {
  createdAt: Generated<Timestamp | null>;
  footerOverride: string | null;
  headerOverride: string | null;
  id: Generated<number>;
  layoutTemplateId: number | null;
  metadataOverride: string | null;
  portalId: number | null;
  updatedAt: Generated<Timestamp | null>;
}

export interface Portals {
  accessType: Generated<string>;
  acknowledgmentDueDays: number | null;
  acknowledgmentMode: Generated<string | null>;
  acknowledgmentReminderDays: number | null;
  allowedRoles: string[] | null;
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  isActive: Generated<boolean>;
  label: string | null;
  minimumReadingTimeSeconds: Generated<number | null>;
  name: string;
  organizationId: number;
  passwordHash: string | null;
  requireFullScroll: Generated<boolean | null>;
  requiresAcknowledgment: Generated<boolean | null>;
  slug: string;
  updatedAt: Generated<Timestamp>;
}

export interface PortalSettings {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  portalId: number;
  settingKey: string;
  settingValue: Json | null;
  updatedAt: Generated<Timestamp>;
}

export interface Sessions {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp | null>;
  userId: number;
}

export interface Settings {
  createdAt: Generated<Timestamp | null>;
  description: string | null;
  id: Generated<number>;
  organizationId: number;
  settingKey: string;
  settingValue: Generated<Json>;
  updatedAt: Generated<Timestamp | null>;
}

export interface UnacknowledgedRequiredPolicies {
  dueDate: Timestamp | null;
  organizationId: number | null;
  policyId: number | null;
  portalId: number | null;
  portalName: string | null;
  reminderDate: Timestamp | null;
  title: string | null;
  urgencyStatus: string | null;
  userEmail: string | null;
  userId: number | null;
  userName: string | null;
}

export interface UserPasswords {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  passwordHash: string;
  userId: number;
}

export interface Users {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp | null>;
  displayName: string;
  email: string;
  firstLoginAt: Timestamp | null;
  firstName: string | null;
  hasLoggedIn: Generated<boolean | null>;
  id: Generated<number>;
  isActive: Generated<boolean | null>;
  lastName: string | null;
  organizationId: number;
  role: Generated<UserRole>;
  updatedAt: Generated<Timestamp | null>;
}

export interface UserGoogleDriveConnections {
  id: Generated<number>;
  userId: number;
  accessToken: string;
  refreshToken: string | null;
  expiresAt: Timestamp | null;
  googleEmail: string | null;
  createdAt: Generated<Timestamp | null>;
  updatedAt: Generated<Timestamp | null>;
}

export interface DB {
  acknowledgmentConfirmationCodes: AcknowledgmentConfirmationCodes;
  emailBasedAcknowledgments: EmailBasedAcknowledgments;
  layoutTemplates: LayoutTemplates;
  loginAttempts: LoginAttempts;
  notifications: Notifications;
  oauthAccounts: OauthAccounts;
  oauthStates: OauthStates;
  organizationDownloadSettings: OrganizationDownloadSettings;
  organizations: Organizations;
  organizationVariables: OrganizationVariables;
  policies: Policies;
  policyAcknowledgments: PolicyAcknowledgments;
  policyAssignments: PolicyAssignments;
  policyAuditLog: PolicyAuditLog;
  policyDownloads: PolicyDownloads;
  policyPortalAssignments: PolicyPortalAssignments;
  policyReadingSessions: PolicyReadingSessions;
  policyVersions: PolicyVersions;
  portalEmailRecipients: PortalEmailRecipients;
  portalLayoutOverrides: PortalLayoutOverrides;
  portals: Portals;
  portalSettings: PortalSettings;
  sessions: Sessions;
  settings: Settings;
  unacknowledgedRequiredPolicies: UnacknowledgedRequiredPolicies;
  userGoogleDriveConnections: UserGoogleDriveConnections;
  userPasswords: UserPasswords;
  users: Users;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = ["admin","approver","editor","user"];
// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.